baseURL = 'https://rippreport.com/'
languageCode = 'en-us'
title = 'Ripp Report'
theme = 'mainroad'

[Author] # Used in authorbox
  name = "Francis Ripp"
  bio = ""
  avatar = "img/eagle.png"

[Params]
  description = "Reporting on the political corruption in Fairhope, AL and Baldwin County." # Site description. Used in meta description
  copyright = "Rippreport"
  twitter_cards = true 
  readmore = true 
  authorbox = false 
  toc = false 
  pager = true 
  post_meta = ["date", "categories"]
  mainSections = ["p"]
  customCSS = ["css/custom.css"]
  mathjax = false

[Params.sidebar]
  home = "right"   # layout for home page
  list = "right"   # layout for list pages
  single = "right" # layout for single pages
  widgets = ["search", "recent", "taglist"]

[Params.widgets]
  recent_num = 10 # Number of articles in the "Recent articles" widget
  tags_counter = false

[Params.style.vars]
  highlightColor = "#176898" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
