baseURL = 'https://rippreport.com/'
languageCode = 'en-us'
title = 'Ripp Report'
theme = 'mainroad'
disableHugoGeneratorInject = true
logo = "https://rippreport.com/img/eagle.png"

[Author] # Used in authorbox
  name = "Francis Ripp"
  bio = ""
  avatar = "img/eagle.svg"

[Params]
  description = "Reporting on the political corruption in Fairhope, AL and Baldwin County." 
  twitter_cards = true 
  readmore = true 
  authorbox = false 
  toc = false 
  pager = true 
  post_meta = ["date"]
  mainSections = ["p"]
  mathjax = false
  opengraph = true
  #customCSS = ["css/custom.css"] # Include custom CSS files
  #googleFontsLink = "https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&family=Vina+Sans&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
[Params.sidebar]
  home = "right"   # layout for home page
  list = "right"   # layout for list pages
  single = "right" # layout for single pages
  widgets = ["recent"]

[Params.widgets]
  recent_num = 12 # Number of articles in the "Recent articles" widget
  tags_counter = false

[Params.style.vars]
  highlightColor = "#176898"
  fontFamilyPrimary =  "sans;"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
