baseURL = 'https://rippreport.com/'
languageCode = 'en-us'
title = 'Ripp Report'
theme = 'mainroad'
disableHugoGeneratorInject = true
logo = "https://rippreport.com/img/eagle.png"

[Author] # Used in authorbox
  name = "Francis Ripp"
  bio = ""
  avatar = "img/eagle.svg"

[Params]
  description = "Reporting on the political corruption in Fairhope, AL and Baldwin County." 
  twitter_cards = true 
  readmore = true
  authorbox = false 
  toc = false 
  pager = true 
  post_meta = ["date", "categories"]
  mainSections = ["p"]
  mathjax = false
  comments = false
  customCSS = ["css/custom.css"] 
[Params.sidebar]
  widgets = ["search", "recent"]

[Params.widgets]
  recent_num = 10 # Number of articles in the "Recent articles" widget
  tags_counter = false

[Params.style.vars]
  highlightColor = "#176898"
  fontFamilyPrimary =  "sans;"


[markup]
  [markup.asciidocExt]
    safeMode = 'unsafe'
	unsafe = true
	xhtml = false