name = "comments-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for storing comments
[[kv_namespaces]]
binding = "COMMENTS_KV"
preview_id = "30cdc5258e904c849953423307a92a3d"
id = "4645b7959b39496e9ee1f4970a64a7da"

# Environment variables for configuration
[vars]
ALLOWED_ORIGINS = "http://localhost:1313,https://rippreport.com,https://www.rippreport.com"
RATE_LIMIT_WINDOW = "60"
RATE_LIMIT_MAX = "3"

# Production environment configuration
[env.production]
name = "comments-api-prod"

[[env.production.kv_namespaces]]
binding = "COMMENTS_KV"
preview_id = "30cdc5258e904c849953423307a92a3d"
id = "4645b7959b39496e9ee1f4970a64a7da"

[env.production.vars]
ALLOWED_ORIGINS = "https://rippreport.com,https://www.rippreport.com"
RATE_LIMIT_WINDOW = "60"
RATE_LIMIT_MAX = "3"

# Development environment configuration  
[env.development]
name = "comments-api-dev"

[[env.development.kv_namespaces]]
binding = "COMMENTS_KV"
preview_id = "30cdc5258e904c849953423307a92a3d"
id = "4645b7959b39496e9ee1f4970a64a7da"

[env.development.vars]
ALLOWED_ORIGINS = "http://localhost:1313,https://rippreport.com,https://www.rippreport.com"
RATE_LIMIT_WINDOW = "60"
RATE_LIMIT_MAX = "3"